spring.application.name=societymanagement
# Server Configuration
server.port=8080
#server.servlet.context-path=/api

# MongoDB Configuration
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/societymanagement
# OR for MongoDB Atlas:
# mongodb+srv://:<>@societymanagementapp.jkyhqdz.mongodb.net/?appName=SocietyManagementApp

spring.data.mongodb.database=societymanagement

# Auto-create indexes
spring.data.mongodb.auto-index-creation=true


# Logging
logging.level.root=INFO
logging.level.com.society.management=DEBUG

# JWT Configuration
jwt.secret.access=YourVeryLongAccessTokenSecretKeyMinimum64CharactersForProductionChangeThis2024SecurityKey
jwt.secret.refresh=YourVeryLongRefreshTokenSecretKeyMinimum64CharactersForProductionChangeThis2024SecurityKey
jwt.expiration.access=3600000
jwt.expiration.refresh=86400000

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chaurasiapratham16@gmail.com
spring.mail.password=enfr tqzk mlbs uhyq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Cloudinary Configuration
cloudinary.cloud-name=dyihbfi5m
cloudinary.api-key=972977755321764
cloudinary.api-secret=dgeKO4xwLbYBjxyaMpbNB61Xfvg

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Application Specific
app.society.default-code=DEMO123
app.otp.expiry-minutes=5

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
